### ISSUE TITLE
Suggestion: Base on datascience-notebook

### ISSUE THREAD

**Issue by meggart** [esa-esdl/jupyterhub-swarm#16]
Would it make sense to base our container not on notebook-base but on https://github.com/jupyter/docker-stacks/tree/master/datascience-notebook ? Then we would have recent versions of R and Julia already installed including the most important packages which would facilitate maintenance and especially future upgrades of Julia and R. In particular, I could test the Julia installation locally, since I can run this container on my machine, maybe we add the changes to start.sh etc at the very end of the container build, then one can still launch the container locally for testing and then apply the Service-specific changes on top of the packages in an extra build step.

**Comment by dzelge** [comment]
Hello Fabian,

Sorry for the late reply. I have been thinking the very same thought since a while. I did not attempt to change it as the system was running, but  I'll create a PR then we can test whether it does what we want. Will take a mo tho.

Helge

**Comment by dzelge** [comment]
Done
