### ISSUE TITLE
Some R packages not installing

### ISSUE THREAD

**Issue by dzelge** [esa-esdl/jupyterhub-swarm#26]
__Expected Behaviour__:

See [Forum](https://forum.earthsystemdatalab.net/t/installing-r-packages-fail/112)

**Comment by AliceBalfanz** [comment]
included conda package installation on branch [alicja-25-synchronizing-jupyterhub-versions](https://github.com/esa-esdl/jupyterhub-swarm/tree/alicja-25-synchronizing-jupyterhub-versions)
